version: '2'
services:
  database:
    image: postgres:latest
    expose:
      - 5432
    env_file:
      - database/database.env
    volumes:
      - "/c/Users/Ockle1P/dev/git_repos/ockleford/upskilling/aws/master_acceptance_database/database:/scripts"